export enum EventItem {
  /**  空格 */
  EMPTY = 0,
  /**  新空格 */
  NEW_EMPTY = 1,
  /** 牆壁 */
  WALL = 10,
  /** 障礙物 */
  OBSTACLE = 15,
  /** 核心 */
  CORE_1_LEFT = 20,
  CORE_2_LEFT = 21,
  CORE_3_LEFT = 22,
  CORE_4_LEFT = 23,
  CORE_5_LEFT = 24,
  CORE_1_RIGHT = 25,
  CORE_2_RIGHT = 26,
  CORE_3_RIGHT = 27,
  CORE_4_RIGHT = 28,
  CORE_5_RIGHT = 29,
  /** 陷阱 */
  TRAP = 30,
  /** 陷阱_左邊 */
  TRAP_LEFT = 31,
  /** 陷阱_右邊 */
  TRAP_RIGHT = 32,
  /** 時光機_左邊 */
  TIME_MACHINE_LEFT = 40,
  /** 時光機_左邊 */
  TIME_MACHINE_RIGHT = 41,
}
